name = "AI Blog Content Generator"
client_id = ""
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
# Read and write access to blog articles and themes
scopes = "write_products,read_products,write_script_tags,read_script_tags,write_themes,read_themes,write_articles,read_articles"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"







