# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "362bd33ead340c7aca3a5b1b11571369"
name = "AI Blog Post Generator "
application_url = "https://matches-drivers-rid-minimal.trycloudflare.com"
embedded = true
handle = "ai-blog-post-generator-1"

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [ "https://matches-drivers-rid-minimal.trycloudflare.com/api/auth" ]

[pos]
embedded = false
